In [48]:
import pandas as pd
import numpy as np

In [49]:
dataset = pd.read_csv(r"C:\Users\Admin\Desktop\TANPHAT\Dự án_canhan\TIKTOK_V2\clustering\dataset\data_creator_final.csv")

In [50]:
dataset.columns

Index(['CREATOR_ID', 'VIDEO_ID', 'CREATE_TIME', 'FOLLOWERS', 'FOLLOWING_COUNT',
       'ENGAGEMENT', 'TOTAL_LIKES', 'DIGG_COUNT', 'VIDEO_COUNT',
       'COLLAB_SCORE', 'PRICE', 'CATEGORY_x', 'BROADCAST_SCORE',
       'ANCHOR_TYPES', 'VIEW_COUNT', 'LIKE_COUNT', 'COMMENT_COUNT',
       'SHARE_COUNT', 'SAVE_COUNT', 'VQSCORE', 'BITRATE', 'CATEGORY_TYPE',
       'CATEGORY_y', 'PRICE_NUM'],
      dtype='object')

In [51]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208411 entries, 0 to 208410
Data columns (total 24 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   CREATOR_ID       208411 non-null  object
 1   VIDEO_ID         208411 non-null  int64
 2   CREATE_TIME      208411 non-null  object
 3   FOLLOWERS        208411 non-null  int64
 4   FOLLOWING_COUNT  208411 non-null  int64
 5   ENGAGEMENT       208411 non-null  float64
 6   TOTAL_LIKES      208411 non-null  int64
 7   DIGG_COUNT       208411 non-null  int64
 8   VIDEO_COUNT      208411 non-null  int64
 9   COLLAB_SCORE     206011 non-null  float64
 10  PRICE            0 non-null       float64
 11  CATEGORY_x       0 non-null       float64
 12  BROADCAST_SCORE  85257 non-null   float64
 13  ANCHOR_TYPES     37252 non-null   object
 14  VIEW_COUNT       208411 non-null  int64
 15  LIKE_COUNT       208411 non-null  int64
 16  COMMENT_COUNT    208411 non-null  int64
 17  SHARE_COUNT      208411 non-null  int64
 18  SAVE_COUNT       208411 non-null  int64
 19  VQSCORE          199828 non-null  float64
 20  BITRATE          199828 non-null  float64
 21  CATEGORY_TYPE    208411 non-null  int64
 22  CATEGORY_y       206461 non-null  object
 23  PRICE_NUM        208411 non-null  float64
dtypes: float64(8), int64(12), object(4)
memory usage: 38.2+ MB

In [52]:
dataset.describe()

,VIDEO_ID,FOLLOWERS,FOLLOWING_COUNT,ENGAGEMENT,TOTAL_LIKES,DIGG_COUNT,VIDEO_COUNT,COLLAB_SCORE,PRICE,CATEGORY_x,BROADCAST_SCORE,VIEW_COUNT,LIKE_COUNT,COMMENT_COUNT,SHARE_COUNT,SAVE_COUNT,VQSCORE,BITRATE,CATEGORY_TYPE,PRICE_NUM
count,2.084110e+05,2.084110e+05,208411.000000,208411.000000,2.084110e+05,208411.000000,208411.000000,206011.000000,0.0,0.0,85257.000000,2.084110e+05,2.084110e+05,208411.000000,2.084110e+05,208411.000000,199828.000000,1.998280e+05,208411.000000,2.084110e+05
mean,7.605272e+18,4.925653e+05,361.369453,5.200031,1.516683e+07,17146.673842,1708.815360,80.051444,NaN,NaN,93.655498,1.892985e+05,7.074886e+03,99.022192,1.801970e+03,493.467701,65.715083,1.244605e+06,111.307517,1.145703e+07
std,9.850599e+15,1.114566e+06,1161.175176,5.662587,3.197799e+07,40132.916780,2994.299342,5.841928,NaN,NaN,2.654832,8.458861e+05,3.427162e+04,1372.297055,3.350897e+04,2762.694742,11.582906,6.561830e+05,7.322685,9.629198e+07
min,7.561749e+18,4.864000e+03,0.000000,0.120000,1.712000e+03,0.000000,1.000000,61.200000,NaN,NaN,90.100000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,4.630900e+04,100.000000,1.000000e+00
25%,7.596817e+18,7.550000e+04,13.000000,2.240000,1.800000e+06,1339.000000,380.000000,76.100000,NaN,NaN,91.100000,6.288000e+03,1.390000e+02,3.000000,3.000000e+00,9.000000,63.320000,8.015255e+05,104.000000,5.000000e+05
50%,7.605474e+18,1.845000e+05,57.000000,3.760000,4.700000e+06,4902.000000,880.000000,78.300000,NaN,NaN,93.200000,2.290000e+04,6.260000e+02,14.000000,2.000000e+01,41.000000,67.990000,1.116518e+06,111.000000,2.000000e+06
75%,7.614333e+18,4.282000e+05,202.000000,6.730000,1.450000e+07,16100.000000,1763.000000,82.900000,NaN,NaN,95.800000,9.860000e+04,3.101000e+03,47.000000,1.640000e+02,210.000000,71.470000,1.538041e+06,120.000000,5.000000e+06
max,7.621386e+18,2.120000e+07,10000.000000,94.160000,4.899000e+08,554300.000000,35900.000000,98.800000,NaN,NaN,100.000000,6.860000e+07,3.600000e+06,485100.000000,6.600000e+06,295949.000000,91.640000,3.813821e+07,120.000000,2.631000e+09

In [53]:
# Groupby và tính toán
from itertools import count


agg_result = dataset.groupby('CREATOR_ID').agg({
    'VIDEO_ID': 'count'    # Đếm số lượng video     #
}).reset_index()

# Lọc: Ví dụ tìm các Creator có lỗi dữ liệu (View < 0)
error_creators = agg_result[agg_result['VIDEO_ID'] <= 1  ]
error_creators1 = agg_result[agg_result['VIDEO_ID'] <= 0 ]
print(len(error_creators))
print(len(error_creators1))

40
0

In [54]:
# 1. Lọc các dòng bị lỗi Follower
error_creators3 = dataset[dataset['FOLLOWERS'] <= 0]

# 2. Lấy danh sách ID duy nhất (Không trùng lặp)
unique_error_ids = error_creators3['CREATOR_ID'].unique()

# 3. In ra danh sách
print("Danh sách các Creator bị lỗi FOLLOWERS <= 0:")
print(unique_error_ids)

# 4. Đếm xem có bao nhiêu Creator bị lỗi này
print(f"\nTổng số Creator bị lỗi: {len(unique_error_ids)}")

Danh sách các Creator bị lỗi FOLLOWERS <= 0:
[]

Tổng số Creator bị lỗi: 0

In [55]:
# # 1. Tạo từ điển (Dictionary) chứa dữ liệu bạn cung cấp
# # Lưu ý: 1.1M = 1100000, 34.1K = 34100
follower_map = {
    'lang51997': 34100,
    'hoaquynh0000': 596400,
    'huynguyen90409': 170500,
    'le.shushu': 374500,
    'lynnhuynhh_': 285600,
    'haiyen666': 127900,
    'wwkeisha': 328900,
    'drawkn995': 594400,
    'dtdung93': 127700,
    'doublesunday': 1100000,
    'mekemsocmo161': 182200,
    'thuson.beauty': 172400,
    'violet122004': 29100,
    'thucevisu8420': 391200
}

# 2. Cập nhật giá trị vào dataset
# Chỉ cập nhật những dòng mà FOLLOWERS <= 0 và có tên trong danh sách trên
for creator, value in follower_map.items():
    dataset.loc[(dataset['CREATOR_ID'] == creator) & (dataset['FOLLOWERS'] <= 0), 'FOLLOWERS'] = value

# 3. Kiểm tra lại xem còn lỗi không
error_check = dataset[dataset['FOLLOWERS'] <= 0]['CREATOR_ID'].unique()
print("Các Creator vẫn còn lỗi Follower <= 0 (nếu có):", error_check)

Các Creator vẫn còn lỗi Follower <= 0 (nếu có): []

In [56]:
# Cách 1: Sử dụng toán tử 'khác' (!=) - Phổ biến nhất
dataset = dataset[dataset['CREATOR_ID'] != 'thuyanh3232']

# Cách 2: Sử dụng phương thức .query() (Dễ đọc hơn)
# dataset = dataset.query("CREATOR_ID != 'thuyanh3232'")

# Kiểm tra lại số lượng dòng sau khi xóa
print(f"Số dòng còn lại: {len(dataset)}")

# Xác nhận xem còn tên đó không (Kết quả nên là False)
print('thuyanh3232' in dataset['CREATOR_ID'].values)

Số dòng còn lại: 208411
False

In [57]:
count_na_per_row = dataset.isna().sum(axis=1)
print(count_na_per_row)

0         4
1         3
2         3
3         3
4         4
         ..
208406    3
208407    4
208408    3
208409    4
208410    3
Length: 208411, dtype: int64

In [58]:
dup = dataset['VIDEO_ID'].duplicated().mean()
print("Duplicate VIDEO_ID %:", dup)

Duplicate VIDEO_ID %: 0.0

In [60]:
dataset

,CREATOR_ID,VIDEO_ID,CREATE_TIME,FOLLOWERS,FOLLOWING_COUNT,ENGAGEMENT,TOTAL_LIKES,DIGG_COUNT,VIDEO_COUNT,COLLAB_SCORE,...,VIEW_COUNT,LIKE_COUNT,COMMENT_COUNT,SHARE_COUNT,SAVE_COUNT,VQSCORE,BITRATE,CATEGORY_TYPE,CATEGORY_y,PRICE_NUM
0,endersff,7574282336460737800,2026-01-09 15:03:48.0000000,433000,96,0.88,8200000,8948,684,87.8,...,11600000,45700,202,1074,1816,69.95,1100586.0,118,"News & Entertainment, Video Games",5000000.0
1,aigonew1ld,7583972786322885889,2025-12-28 15:20:00.0000000,67000,8,11.12,2200000,801,356,81.1,...,16300000,909700,9759,759100,74587,67.28,628871.0,113,"Movies & TV, Pet Tips & Care",12000000.0
2,khucanhhung,7585089116388379911,2025-12-28 20:00:00.0000000,163100,54,5.11,5800000,821,362,84.0,...,268400,7964,158,2353,149,69.48,681045.0,111,"Mukbang & Food Tasting, Home Improvement, Tech...",1500000.0
3,endersff,7585469260718296328,2025-12-25 16:35:31.0000000,433000,96,0.88,8200000,8948,684,87.8,...,10700,78,9,5,6,68.90,1018762.0,102,"News & Entertainment, Video Games",5000000.0
4,hieuride17x,7585789833734737172,2026-01-01 00:00:00.0000000,80600,213,13.80,2800000,136400,256,90.9,...,143200,22300,101,3764,1565,57.63,543016.0,101,"Movies & TV, Music",3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208406,tungss93,7621363717652925716,2026-03-26 08:03:49.0000000,1200000,61,0.81,37800000,346,2934,73.1,...,221,9,0,0,1,58.55,1117785.0,111,"Mukbang & Food Tasting, Other Apparel & Access...",2000000.0
208407,zqnn98,7621365431177153812,2026-03-26 08:10:37.0000000,124700,77,4.82,2400000,2564,1086,90.7,...,256,50,1,0,1,58.49,721358.0,119,"Beauty & Personal Care, Clothing Accessories, ...",1000000.0
208408,violet122004,7621366477081546004,2026-03-26 08:14:39.0000000,29100,0,11.11,1900000,10700,778,76.8,...,341,23,0,13,2,56.36,572598.0,120,"Selfie, Mukbang & Food Tasting, Daily Life",2000000.0
208409,vuvu_thichchill,7621372014573473045,2026-03-26 08:36:09.0000000,220700,245,1.70,3200000,138900,54,71.2,...,7658,11,1,1,2,68.66,1445660.0,118,"Beauty Tutorials & Tips, Restaurant Exploration",1200000.0
208410,zynanh15,7621386291149606165,2026-03-26 09:31:30.0000000,179600,18,15.54,7700000,18300,759,81.0,...,132,43,0,0,1,0.00,838338.0,109,Outfits,1500000.0

In [61]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208411 entries, 0 to 208410
Data columns (total 24 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   CREATOR_ID       208411 non-null  object
 1   VIDEO_ID         208411 non-null  int64
 2   CREATE_TIME      208411 non-null  object
 3   FOLLOWERS        208411 non-null  int64
 4   FOLLOWING_COUNT  208411 non-null  int64
 5   ENGAGEMENT       208411 non-null  float64
 6   TOTAL_LIKES      208411 non-null  int64
 7   DIGG_COUNT       208411 non-null  int64
 8   VIDEO_COUNT      208411 non-null  int64
 9   COLLAB_SCORE     206011 non-null  float64
 10  PRICE            0 non-null       float64
 11  CATEGORY_x       0 non-null       float64
 12  BROADCAST_SCORE  85257 non-null   float64
 13  ANCHOR_TYPES     37252 non-null   object
 14  VIEW_COUNT       208411 non-null  int64
 15  LIKE_COUNT       208411 non-null  int64
 16  COMMENT_COUNT    208411 non-null  int64
 17  SHARE_COUNT      208411 non-null  int64
 18  SAVE_COUNT       208411 non-null  int64
 19  VQSCORE          199828 non-null  float64
 20  BITRATE          199828 non-null  float64
 21  CATEGORY_TYPE    208411 non-null  int64
 22  CATEGORY_y       206461 non-null  object
 23  PRICE_NUM        208411 non-null  float64
dtypes: float64(8), int64(12), object(4)
memory usage: 38.2+ MB

In [62]:



def audit_columns(df, cols):
    results = []

    for col in cols:
        if col not in df.columns:
            results.append({
                "column": col,
                "exists": False
            })
            continue

        series = df[col]
        is_num = pd.api.types.is_numeric_dtype(series)

        results.append({
            "column": col,
            "exists": True,
            "dtype": series.dtype,
            "na_pct": series.isna().mean(),
            "zero_pct": (series == 0).mean() if is_num else None,
            "neg_pct": (series < 0).mean() if is_num else None,
            "mean": series.median() if is_num else None,
            "p90": series.quantile(0.9) if is_num else None,
            "p99": series.quantile(0.99) if is_num else None,
            "max": series.max() if is_num else None,
        })

    return pd.DataFrame(results)


cols_to_check = [
    "VIEW_COUNT",
    "LIKE_COUNT",
    "COMMENT_COUNT",
    "SHARE_COUNT",
    "SAVE_COUNT",
    "CREATE_TIME",
    "CREATOR_ID"
]

audit_report = audit_columns(dataset, cols_to_check)
print(audit_report)

          column  exists   dtype  na_pct  zero_pct  neg_pct     mean  \
0     VIEW_COUNT    True   int64     0.0  0.000197      0.0  22900.0
1     LIKE_COUNT    True   int64     0.0  0.000921      0.0    626.0
2  COMMENT_COUNT    True   int64     0.0  0.078806      0.0     14.0
3    SHARE_COUNT    True   int64     0.0  0.103641      0.0     20.0
4     SAVE_COUNT    True   int64     0.0  0.031265      0.0     41.0
5    CREATE_TIME    True  object     0.0       NaN      NaN      NaN
6     CREATOR_ID    True  object     0.0       NaN      NaN      NaN

        p90        p99         max
0  381300.0  2800000.0  68600000.0
1   13500.0   114000.0   3600000.0
2     156.0     1356.9    485100.0
3    1176.0    27600.0   6600000.0
4     902.0     7714.9    295949.0
5       NaN        NaN         NaN
6       NaN        NaN         NaN

In [63]:
def check_datetime(df, col="CREATE_TIME"):
    try:
        parsed = pd.to_datetime(df[col], errors='coerce')
        return {
            "total": len(parsed),
            "invalid_pct": parsed.isna().mean(),
            "min_time": parsed.min(),
            "max_time": parsed.max()
        }
    except Exception as e:
        return {"error": str(e)}

print(check_datetime(dataset))

{'total': 208411, 'invalid_pct': 0.0, 'min_time': Timestamp('2025-12-23 17:24:07'), 'max_time': Timestamp('2026-03-26 09:31:30')}

In [64]:
dataset["CREATE_TIME"] = pd.to_datetime(
    dataset["CREATE_TIME"], errors="coerce"
)

# kiểm tra
print("Invalid time %:", dataset["CREATE_TIME"].isna().mean())

Invalid time %: 0.0

In [65]:
max_time = dataset["CREATE_TIME"].max()

dataset_3m = dataset[
    dataset["CREATE_TIME"] >= (max_time - pd.DateOffset(months=3))
].copy()

In [66]:
def clean_metric(s):
    s = s.copy()
    s[s < 0] = np.nan
    return s

for col in ["LIKE_COUNT", "COMMENT_COUNT", "SHARE_COUNT", "SAVE_COUNT","VIEW_COUNT"]:
    dataset_3m[col] = clean_metric(dataset_3m[col])

In [67]:
def p90(x):
    return np.nanpercentile(x, 90)

creator_size_reach = (
    dataset_3m
    .groupby("CREATOR_ID")
    .agg(
        # ===== LIKE =====
        MEAN_LIKES_3M=("LIKE_COUNT", "mean"),
        P90_LIKES_3M=("LIKE_COUNT", p90),
        MAX_LIKES_3M=("LIKE_COUNT", "max"),

        # ===== COMMENT =====
        MEAN_COMMENTS_3M=("COMMENT_COUNT", "mean"),
        P90_COMMENTS_3M=("COMMENT_COUNT", p90),
        MAX_COMMENTS_3M=("COMMENT_COUNT", "max"),

        # ===== SHARE =====
        MEAN_SHARES_3M=("SHARE_COUNT", "mean"),
        P90_SHARES_3M=("SHARE_COUNT", p90),
        MAX_SHARES_3M=("SHARE_COUNT", "max"),

        # ===== SAVE =====
        MEAN_SAVES_3M=("SAVE_COUNT", "mean"),
        P90_SAVES_3M=("SAVE_COUNT", p90),
        MAX_SAVES_3M=("SAVE_COUNT", "max"),

        # ===== VIEW =====
        MEAN_VIEWS_3M=("VIEW_COUNT", "mean"),
        P90_VIEWS_3M=("VIEW_COUNT", p90),
        MAX_VIEWS_3M=("VIEW_COUNT", "max"),
        # debug
        VIDEO_COUNT_3M=("VIDEO_ID", "count")
    )
    .reset_index()
)

In [68]:
creator_size_reach.fillna(0, inplace=True)

In [69]:
print((creator_size_reach["VIDEO_COUNT_3M"] < 5).mean())
creator_size_reach.describe().to_csv("creator_size_reach_summary.csv", index=False)

0.058678847505270554

In [70]:
def safe_divide(num, denom):
    return np.where(
        (denom <= 0) | (np.isnan(denom)),
        np.nan,
        num / denom
    )

In [71]:
dataset_3m["VIEW_RATE"] = safe_divide(
    dataset_3m["VIEW_COUNT"], dataset_3m["FOLLOWERS"]
)

dataset_3m["LIKE_RATE"] = safe_divide(
    dataset_3m["LIKE_COUNT"], dataset_3m["VIEW_COUNT"]
)

dataset_3m["COMMENT_RATE"] = safe_divide(
    dataset_3m["COMMENT_COUNT"], dataset_3m["VIEW_COUNT"]
)

dataset_3m["SHARE_RATE"] = safe_divide(
    dataset_3m["SHARE_COUNT"], dataset_3m["VIEW_COUNT"]
)

dataset_3m["SAVE_RATE"] = safe_divide(
    dataset_3m["SAVE_COUNT"], dataset_3m["VIEW_COUNT"]
)

In [72]:
creator_engagement = (
    dataset_3m
    .groupby("CREATOR_ID")
    .agg(
        MEAN_VIEWS_RATE_3M=("VIEW_RATE", "mean"),
        MEAN_LIKE_RATE_3M=("LIKE_RATE", "mean"),
        MEAN_COMMENT_RATE_3M=("COMMENT_RATE", "mean"),
        MEAN_SHARE_RATE_3M=("SHARE_RATE", "mean"),
        MEAN_SAVE_RATE_3M=("SAVE_RATE", "mean"),
    )
    .reset_index()
)

In [73]:
creator_engagement.sort_values("MEAN_VIEWS_RATE_3M", ascending=False).head(10)

,CREATOR_ID,MEAN_VIEWS_RATE_3M,MEAN_LIKE_RATE_3M,MEAN_COMMENT_RATE_3M,MEAN_SHARE_RATE_3M,MEAN_SAVE_RATE_3M
859,hahaohen_08,377.643505,0.067352,0.000324,0.006160,0.004883
1631,nahtviez,179.824561,0.068268,0.000079,0.002732,0.001590
91,_siudangghet,110.346323,0.062802,0.000947,0.079833,0.002795
2767,wuang.san,88.847253,0.055795,0.000470,0.026148,0.003155
1904,pg.vi3,78.802600,0.090595,0.000452,0.016581,0.005932
1548,minhlapriqwe,72.128779,0.047498,0.000829,0.006708,0.005188
2311,thenextfacevn.org,71.371750,0.025033,0.000856,0.005873,0.000887
2241,thaituhmoob0,69.296321,0.027531,0.001028,0.123094,0.001505
1731,nguyenanh0719,56.925544,0.042585,0.001551,0.013358,0.000463
1918,phantuananh67742,54.659399,0.039061,0.000348,0.018573,0.000851

In [74]:
creator_engagement.describe()

,MEAN_VIEWS_RATE_3M,MEAN_LIKE_RATE_3M,MEAN_COMMENT_RATE_3M,MEAN_SHARE_RATE_3M,MEAN_SAVE_RATE_3M
count,2846.000000,2845.000000,2845.000000,2845.000000,2845.000000
mean,2.652824,0.050059,0.001571,0.005037,0.004220
std,9.961376,0.066972,0.005673,0.021093,0.010406
min,0.000000,0.000994,0.000000,0.000000,0.000036
25%,0.210675,0.022382,0.000396,0.000797,0.001282
50%,0.632679,0.035754,0.000700,0.001825,0.002380
75%,2.043260,0.060246,0.001319,0.004394,0.004536
max,377.643505,1.367201,0.181939,0.915909,0.401019

In [75]:
dataset_3m["VIEW_RATE"] = safe_divide(
    dataset_3m["VIEW_COUNT"],dataset_3m["FOLLOWERS"]
)

In [76]:
creator_reach = (
    dataset_3m
    .groupby("CREATOR_ID")
    .agg(
        MEAN_VIEW_RATE_3M=("VIEW_RATE", "mean"),
        P90_VIEW_RATE_3M=("VIEW_RATE", lambda x: np.nanpercentile(x, 90)),
        MAX_VIEW_RATE_3M=("VIEW_RATE", "max")
    )
    .reset_index()
)

In [77]:
result = dataset_3m.loc[dataset_3m['CREATOR_ID'] == 'hahaohen_08', ['FOLLOWERS', 'VIEW_COUNT']]

print(result)

      FOLLOWERS  VIEW_COUNT
4830      33100    12500000

In [78]:
creator_reach.sort_values("MEAN_VIEW_RATE_3M", ascending=False).head(10)

             CREATOR_ID  MEAN_VIEW_RATE_3M  P90_VIEW_RATE_3M  MAX_VIEW_RATE_3M
859         hahaohen_08         377.643505        377.643505        377.643505
1631           nahtviez         179.824561        179.824561        179.824561
91         _siudangghet         110.346323        191.448628        446.713465
2767          wuang.san          88.847253        258.826531        500.000000
1904             pg.vi3          78.802600        206.556738        375.886525
1548       minhlapriqwe          72.128779        147.710487        147.710487
2311  thenextfacevn.org          71.371750        128.374836        142.625608
2241       thaituhmoob0          69.296321        134.034166        394.218134
1731      nguyenanh0719          56.925544         98.416698        343.642612
1918   phantuananh67742          54.659399        212.738188        430.696946

In [79]:
dataset_3m.groupby("CREATOR_ID")["FOLLOWERS"].nunique().value_counts()

FOLLOWERS
1    2846
Name: count, dtype: int64

In [80]:
creator_size_reach["VIDEO_COUNT_3M"].value_counts()
print((creator_size_reach["VIDEO_COUNT_3M"] < 5).mean())

0.058678847505270554

In [81]:
import pandas as pd

# 1. Chuyển đổi sang Date và tìm Global Min/Max Date của toàn bộ chiến dịch 3 tháng
dataset_3m["POST_DATE"] = dataset_3m["CREATE_TIME"].dt.date
global_min_date = dataset_3m["POST_DATE"].min()
global_max_date = dataset_3m["POST_DATE"].max()

# Tính tổng số ngày và tổng số tuần của toàn bộ dataset
global_total_days = (global_max_date - global_min_date).days + 1
global_total_weeks = global_total_days / 7

# 2. Tính khoảng cách giữa các lần đăng bài (GAP)
# Sắp xếp dữ liệu theo Creator và Thời gian đăng để tính diff() chính xác
dataset_3m = dataset_3m.sort_values(by=["CREATOR_ID", "CREATE_TIME"])
dataset_3m["POST_GAP_DAYS"] = dataset_3m.groupby("CREATOR_ID")["CREATE_TIME"].diff().dt.total_seconds() / 86400

# 3. Aggregation: Gom nhóm theo CREATOR_ID và tính toán các chỉ số cơ bản
creator_time = dataset_3m.groupby("CREATOR_ID").agg(
    VIDEO_COUNT_3M=("VIDEO_ID", "count"),      # Đếm tổng số video của creator
    unique_days=("POST_DATE", "nunique"),      # Đếm số ngày có hoạt động
    AVG_POST_GAP=("POST_GAP_DAYS", "mean")     # Tính trung bình khoảng cách giữa các post
).reset_index()

# 4. Tính toán các Feature phái sinh cho mô hình phân cụm
# Tần suất đăng bài theo tuần: Tổng video / Tổng số tuần của tập dữ liệu
creator_time["VIDEOS_PER_WEEK"] = creator_time["VIDEO_COUNT_3M"] / global_total_weeks

# Độ kiên trì/ổn định: Tỷ lệ số ngày có đăng bài trên tổng số ngày của chiến dịch
creator_time["POSTING_CONSISTENCY"] = creator_time["unique_days"] / global_total_days

In [82]:
creator_time

,CREATOR_ID,VIDEO_COUNT_3M,unique_days,AVG_POST_GAP,VIDEOS_PER_WEEK,POSTING_CONSISTENCY
0,._.ehe23,39,28,2.186655,3.000000,0.307692
1,.hoang.kha.71,322,75,0.248959,24.769231,0.824176
2,.k.c.c5,344,88,0.256277,26.461538,0.967033
3,.qkhanh1403,51,33,0.831694,3.923077,0.362637
4,.siudangiu06,41,34,2.182299,3.153846,0.373626
...,...,...,...,...,...,...
2841,ztimu_,3,3,34.492402,0.230769,0.032967
2842,zuohang2006.official,401,69,0.220146,30.846154,0.758242
2843,zybithanhtruc,21,16,4.016425,1.615385,0.175824
2844,zynanh15,85,61,1.071168,6.538462,0.670330
2845,zyycute._,18,18,4.824328,1.384615,0.197802

In [83]:
creator_view = dataset_3m.groupby("CREATOR_ID").agg(
    VIEW_MEAN=("VIEW_COUNT", "mean"),
    VIEW_STD=("VIEW_COUNT", "std"),
    VIDEO_COUNT=("VIDEO_ID", "count")
).reset_index()

creator_view["VIEW_CV"] = (
    creator_view["VIEW_STD"] /
    (creator_view["VIEW_MEAN"] + 1e-6)
)

In [84]:


# 1. Gom nhóm theo CREATOR_ID và tính P90 cùng với Mean
creator_virality = dataset_3m.groupby("CREATOR_ID").agg(
    VIEW_P90=("VIEW_COUNT", lambda x: x.quantile(0.9)),
    VIEW_MEAN_V=("VIEW_COUNT", "mean"),
    VIDEO_COUNT=("VIDEO_ID", "count") # Đếm số video để lọc nhiễu sau này
).reset_index()

# 2. Tính Cường độ bùng nổ (Viral Magnitude)
# Cộng thêm 1e-6 ở mẫu số để tránh lỗi ZeroDivisionError nếu Median = 0
creator_virality["VIRAL_MAGNITUDE"] = (
    creator_virality["VIEW_P90"] / 
    (creator_virality["VIEW_MEAN_V"] + 1e-6)
)

In [85]:

# 1. Tạo cột phong độ bình thường (Mean) cho từng video bằng hàm transform
dataset_3m["VIEW_MEAN_V"] = (
    dataset_3m.groupby("CREATOR_ID")["VIEW_COUNT"]
    .transform("mean")
)

# 2. VIRAL_STRENGTH (Cấp độ Video): 
# Tính xem video này "to" gấp bao nhiêu lần mức bình thường của chính kênh đó
dataset_3m["VIRAL_STRENGTH"] = (
    dataset_3m["VIEW_COUNT"] / (dataset_3m["VIEW_MEAN_V"] + 1e-6)
)

# 3. Gom nhóm lại cho Creator
# Thay vì lấy Mean (bị nhiễu bởi các video lẹt đẹt), ta lấy MAX (Video bùng nổ nhất) 
# và Mean của những video thực sự Viral (Strength > 1)
creator_virality_intensity = dataset_3m.groupby("CREATOR_ID").agg(
    MAX_VIRAL_STRENGTH=("VIRAL_STRENGTH", "max"),  # Kỷ lục bùng nổ của kênh là gấp bao nhiêu lần?
    AVG_VIRAL_STRENGTH=("VIRAL_STRENGTH", "mean")  # (Tùy chọn) Trung bình sức mạnh của toàn bộ video
).reset_index()

# Gộp vào bảng creator_virality tổng mà chúng ta đã làm ở bước trước
creator_virality = creator_virality.merge(creator_virality_intensity, on="CREATOR_ID", how="left")

In [86]:
def check_creator_key(df, name):
    if "CREATOR_ID" not in df.columns:
        print(f"[ERROR] {name}: missing CREATOR_ID")
        return
    
    n_rows = len(df)
    n_unique = df["CREATOR_ID"].nunique(dropna=False)
    n_dup = df.duplicated(subset=["CREATOR_ID"]).sum()
    
    print(f"{name}: rows={n_rows:,}, unique_creators={n_unique:,}, duplicate_keys={n_dup:,}")
    
    if n_dup > 0:
        print(df[df.duplicated(subset=["CREATOR_ID"], keep=False)]
              .sort_values("CREATOR_ID")
              .head(10))

In [87]:
for name, df in {
    "creator_size_reach": creator_size_reach,
    "creator_engagement": creator_engagement,
    "creator_time": creator_time,
    "creator_view": creator_view[["CREATOR_ID", "VIEW_MEAN", "VIEW_STD", "VIEW_CV", "VIDEO_COUNT"]],
    "creator_virality": creator_virality
}.items():
    check_creator_key(df, name)

creator_size_reach: rows=2,846, unique_creators=2,846, duplicate_keys=0
creator_engagement: rows=2,846, unique_creators=2,846, duplicate_keys=0
creator_time: rows=2,846, unique_creators=2,846, duplicate_keys=0
creator_view: rows=2,846, unique_creators=2,846, duplicate_keys=0
creator_virality: rows=2,846, unique_creators=2,846, duplicate_keys=0

In [88]:
from functools import reduce

creator_feature_tables = [
    creator_size_reach,
    creator_engagement,
    creator_time,
    creator_view[["CREATOR_ID", "VIEW_MEAN", "VIEW_STD", "VIEW_CV", "VIDEO_COUNT"]],
    creator_virality
]

creator_features = reduce(
    lambda left, right: pd.merge(
        left, right, on="CREATOR_ID", how="outer", validate="one_to_one"
    ),
    creator_feature_tables
)

In [89]:
# 1) rút data gốc về đúng 1 dòng / 1 creator
creator_base = dataset.groupby("CREATOR_ID", as_index=False).first()

# 2) merge với bảng feature creator-level
creator_main = creator_base.merge(
    creator_features,
    on="CREATOR_ID",
    how="left",
    validate="one_to_one"
)

print(creator_main.shape)
print("Unique creators:", creator_main["CREATOR_ID"].nunique())
print("Duplicate CREATOR_ID:", creator_main.duplicated("CREATOR_ID").sum())

(2849, 60)
Unique creators: 2849
Duplicate CREATOR_ID: 0

In [91]:
creator_main.to_csv(".\\clustering\\dataset\\creator_features_final4.csv", index=False)

OSError: Cannot save file into a non-existent directory: 'clustering\dataset'